aws-windows-deployment-manifest.json, azure-pipelines.yml, buildspec.yml
=> Devops codebuild initial

ClientApp/src/__snapshots__/storyshots.test.ts.snap, ClientApp/src/components/Tag/Tag.stories.tsx, ClientApp/src/components/Tag/Tag.tsx, ClientApp/src/containers/Roster/Roster.tsx, docker-compose.yaml
=> 2: Adds funding column to roster 

ClientApp/.env, ClientApp/Dockerfile-dev, ClientApp/entrypoint.sh, Makefile, README.md, dc, dc-backend, dc-client, dc-dotnet, dc-sqlcmd, dc-yarn, docker-compose-windows.yaml
Fully support Docker development on Windows with only the addition of an environment variable.
(This isn't a perfect solution, of course, but it provides a consistent experience across all platforms. And is much better than previous solutions.)
=> Support windows development with docker

buildspec.yml
=> aws codebuild (#24)

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/yarn.lock
Simple dependency update. Needed to update typescript to pull in bug fix for infinite loop of "Files successfully emitted, waiting for typecheck results..." → " Compiled successfully!". Only saw that in Docker, not sure if others too.
Unfortunately this doesn't solve high CPU usage which is what I was checking out, particularly in the client container. But hey, it's one thing ruled out.
=> Update typescript and CRA

azure-pipelines.yml, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Schema/Types/EnrollmentType.cs, src/Hedwig/Schema/Types/SiteType.cs, test/HedwigTests/Integration/GraphQLTests.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs
Adds arguments to EnrollmentRepository fields, expose queryable interface for more modular searching.
I'm very much not sure if this is a good way about implementing this. @jlhogan If there's an article you reference about your structure of sub-queries, I would love to take a look! None of the documentation I found describes the structure we have, so I read between the lines and came up with this.
Should resolve #4
=> Add filter for enrollments by date (#4)

test/HedwigTests/Helpers/ChildHelper.cs, test/HedwigTests/Helpers/EnrollmentHelper.cs, test/HedwigTests/Helpers/FamilyDeterminationHelper.cs, test/HedwigTests/Helpers/FundingHelper.cs, test/HedwigTests/Helpers/SiteHelper.cs, test/HedwigTests/Helpers/UserHelper.cs, test/HedwigTests/Integration/GraphQLQueries/ChildQueryTests.cs, test/HedwigTests/Integration/GraphQLQueries/EnrollmentQueryTests.cs, test/HedwigTests/Integration/GraphQLQueries/UserQueryTests.cs, test/HedwigTests/Repositories/ChildRepositoryTests.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs, test/HedwigTests/Repositories/FamilyDeterminationRepositoryTests.cs, test/HedwigTests/Repositories/FundingRepositoryTests.cs
=> Refactor test helpers

docker-compose.test.yaml, src/Hedwig/Schema/Types/ReportType.cs, src/Hedwig/Security/AuthorizationEvaluator.cs, src/Hedwig/Security/Permissions.cs, test/HedwigTests/Fixtures/TestAuthenticationHandler.cs, test/HedwigTests/Helpers/AuthorizationRequirementHelper.cs, test/HedwigTests/Integration/GraphQLQueries/ChildQueryPermissionsTests.cs, test/HedwigTests/Integration/GraphQLQueries/EnrollmentQueryPermissionsTests.cs, test/HedwigTests/Integration/GraphQLQueries/ReportQueryPermissionsTests.cs, test/HedwigTests/Integration/GraphQLQueries/UserQueryPermissionsTests.cs, test/HedwigTests/Security/AuthorizationEvaluatorTests.cs, test/HedwigTests/Security/AuthorizationRuleTests.cs, test/HedwigTests/Security/AuthorizationRulesTests.cs, test/HedwigTests/Security/AuthorizationSettings.cs, test/HedwigTests/Security/Policies/AuthenticatedUserRequirementTests.cs, test/HedwigTests/Security/Policies/CurrentUserRequirementTests.cs, test/HedwigTests/Security/Policies/DeveloperUserRequirementTests.cs, test/HedwigTests/Security/Policies/DevelopmentRequirementTests.cs, test/HedwigTests/Security/Policies/TestModeRequirementTests.cs
Add tests of the authentication and authorization system, both unit and integration.
=> Add authentication/authorization tests

src/Hedwig/Migrations/20191029174036_AddFieldsToFamily.Designer.cs, src/Hedwig/Migrations/20191029174036_AddFieldsToFamily.cs, src/Hedwig/Migrations/20191029190603_RemoveCaseNumberFromFamily.Designer.cs, src/Hedwig/Migrations/20191029190603_RemoveCaseNumberFromFamily.cs, src/Hedwig/Models/Family.cs, src/Hedwig/Repositories/ChildRepository.cs, src/Hedwig/Schema/Types/FamilyType.cs, test/HedwigTests/Integration/GraphQLQueries/ChildQueryTests.cs, test/HedwigTests/Repositories/ChildRepositoryTests.cs, test/HedwigTests/Repositories/FamilyRepositoryTests.cs
=> Update Family model (Issue 185)

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-components.scss, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-general.scss, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-typography.scss, src/Hedwig/ClientApp/src/assets/styles/index.scss, src/Hedwig/ClientApp/src/components/Dropdown/Dropdown.stories.tsx, src/Hedwig/ClientApp/src/components/Dropdown/Dropdown.tsx, src/Hedwig/ClientApp/yarn.lock
This component raised a few odd little problems:
- Needed to define theme image path and font path relative to USWDS files using them
- Due to a [bug](https://github.com/uswds/uswds/issues/3117), uswds-theme-components was not included by default, so those are now included in index.scss
- Defining the image path broke the hero image path, because it used image path by default but was used in a different place-- upgrade to USWDS 2.2.1 fixed this by allowing us to set hero-image-path
=> Create dropdown component (#131)

src/Hedwig/Migrations/20191104162026_AddBirthLocationSasidFosterNullableBirthDateAndGenderRemoveNullableBoolFromChild.Designer.cs, src/Hedwig/Migrations/20191104162026_AddBirthLocationSasidFosterNullableBirthDateAndGenderRemoveNullableBoolFromChild.cs, src/Hedwig/Models/Child.cs, src/Hedwig/Schema/AppErrorMessages.cs, src/Hedwig/Schema/Types/ChildType.cs
=> 187 Update Child model

src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Migrations/20191104193346_AddNullableAgeAndEntryToEnrollment.Designer.cs, src/Hedwig/Migrations/20191104193346_AddNullableAgeAndEntryToEnrollment.cs, src/Hedwig/Models/Age.cs, src/Hedwig/Models/Enrollment.cs, src/Hedwig/Schema/Types/EnrollmentType.cs
=> 188 update enrollment model

src/Hedwig/Models/Age.cs, src/Hedwig/Schema/Mutations/EnrollmentMutation.cs, src/Hedwig/Schema/Types/AgeEnumType.cs, src/Hedwig/Schema/Types/EnrollmentType.cs, test/HedwigTests/Helpers/EnrollmentHelper.cs, test/HedwigTests/Integration/GraphQLMutations/EnrollmentMutationTests.cs
=> 189 enrollment update

src/Hedwig/Schema/Mutations/FamilyMutation.cs, test/HedwigTests/Integration/GraphQLMutations/FamilyMutationTests.cs
=> Add update family mutation

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/Alert/Alert.tsx, src/Hedwig/ClientApp/src/containers/ReportDetail/ReportSubmitForm.tsx
Not sure if alert should go away at some point, or have an x, or if we just let it disappear into the ether when a user navigates elsewhere
=> Add success to report

src/Hedwig/Controllers/OrganizationController.cs, src/Hedwig/Controllers/SitesController.cs, src/Hedwig/Controllers/UsersController.cs
Proof of concept for nested routes. It looks like Dotnet Core will give us everything we need for our Spec write up!
Connects #231
=> POC for nested routes

azure-pipelines.yml
=> Remove frontend test publication

src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Migrations/20191115234759_AddOrganizationIdToFamily.Designer.cs, src/Hedwig/Migrations/20191115234759_AddOrganizationIdToFamily.cs, src/Hedwig/Migrations/20191118164730_AddOrganizationIdToChild.Designer.cs, src/Hedwig/Migrations/20191118164730_AddOrganizationIdToChild.cs, src/Hedwig/Models/Child.cs, src/Hedwig/Models/Family.cs, src/Hedwig/Models/Site.cs, test/HedwigTests/Helpers/ChildHelper.cs, test/HedwigTests/Helpers/FamilyHelper.cs
Also, sets OnDelete = restrict for _ALL_ fks with a custom
ModelBuilderExtension method
closes #265
=> 265: Adds organizationId to family

src/Hedwig/Controllers/ChildrenController.cs, src/Hedwig/Controllers/HedwigController.cs, src/Hedwig/Repositories/ChildRepository.cs, src/Hedwig/Repositories/FamilyRepository.cs, src/Hedwig/Schema/Mutations/FamilyDeterminationMutation.cs, src/Hedwig/Schema/Mutations/FamilyMutation.cs, src/Hedwig/Schema/Types/ChildType.cs, src/Hedwig/Schema/Types/FamilyDeterminationType.cs, test/HedwigTests/Controllers/ChildrenControllerTests.cs, test/HedwigTests/Fixtures/TestContextProvider.cs, test/HedwigTests/Fixtures/TestHedwigContext.cs, test/HedwigTests/Helpers/ChildHelper.cs, test/HedwigTests/Repositories/ChildRepositoryTests.cs, test/HedwigTests/Repositories/FamilyRepositoryTests.cs
closes #252 
includes commit from PR #286 which should be merged first
=> 252 children

src/Hedwig/ClientApp/public/config.json, src/Hedwig/ClientApp/src/config.ts, src/Hedwig/ClientApp/src/contexts/Login/LoginHOC.tsx, src/Hedwig/ClientApp/src/index.tsx, src/Hedwig/ClientApp/src/utils/getCurrentHost.ts, src/Hedwig/ServiceExtensions.cs, src/Hedwig/Startup.cs, src/Hedwig/appsettings.Development.json, src/Hedwig/appsettings.json
It looks like your suggestion will work! (We just need to confirm that there aren't any optimizations during the build phase that will prevent us from reading the value at runtime)
=> Use config file for React App OpenID url

src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Hedwig.csproj, src/Hedwig/Startup.cs
to see the basic openAPI generated without any custom decoration etc,
visit /swagger/v1/swagger.json
=> Adds OpenAPI support to backend with Swashbuckle

hedwig-1.0.0-OAS.yaml, rest-backend/db.json, rest-backend/routes.json, src/Hedwig/ClientApp/src/OAS-generated/models/User.ts, src/Hedwig/ClientApp/src/containers/Reports/Reports.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/contexts/User/UserContext.tsx, src/Hedwig/ClientApp/src/hooks/useOASClient.ts, src/Hedwig/ClientApp/src/index.tsx, src/Hedwig/ClientApp/src/utils/queryParamDateFormatter.ts, src/Hedwig/appsettings.Development.json
Thank you @cailyncodes for pairing on this!  :tada:
=> 296 user context

src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx
Also reformats some spaces to tabs for consistency
=> Use enrollment

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/Button/Button.tsx, src/Hedwig/ClientApp/src/components/DatePicker/DatePicker.tsx, src/Hedwig/ClientApp/src/components/RadioGroup/RadioButton.tsx, src/Hedwig/ClientApp/src/containers/Roster/DateSelectionForm.tsx, src/Hedwig/ClientApp/src/utils/dateFormatter.ts
The main issue was that the default button type was submit in the context of a form.
=> 328 datepicker logout fix

src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/hooks/useApi.ts, src/Hedwig/ClientApp/src/utils/getIdForUser.ts, src/Hedwig/Controllers/UsersController.cs, test/HedwigTests/Controllers/ReportsControllerTests.cs, test/HedwigTests/Controllers/UsersControllerTests.cs, test/HedwigTests/Helpers/ReportHelper.cs, test/HedwigTests/Repositories/ReportRepositoryTests.cs
- util to get ids from user in client
- fixup enrollment detail view to display enrollment
- add tests for reports controller and repo function
- add test for user controller
=> Some housekeeping

azure-pipelines.yml, installer/tf/prsystem/tf-pr-system-destroy.bat, installer/tf/prsystem/tf-pr-system-destroy.sh
The hedwig staging environment is currently being updated via the Azure DevOps Service CI/CD pipeline for both master and PR branch builds. The hedwig staging environment should only be updated for master builds.
=> added conditional for publish for master (#350)

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss, src/Hedwig/ClientApp/src/components/Tag/Tag.tsx, src/Hedwig/ClientApp/src/containers/ReportDetail/ReportDetail.tsx
Also fixed some spacing and moved background-color-related CSS to one place so it's easier to find/change
=> Add draft tag to unsubmitted reports

src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/utils/enrollmentTextFormatter.ts, src/Hedwig/ClientApp/src/utils/getColorForFundingType.ts
Addresses #219 except for the "child summary page styling" bullet, which was decided in Slack to be left for later
=> All quick fixes done except child summary page styling

docs/authorization/2019_10_24_graphql-authorization.md, docs/backend/2019_11_25_graphql-to-rest.md, docs/lad-template.md
Restructure docs folder; add LAD template; and add GraphQL to REST LAD; Supercede GraphQL Authorization LAD
=> Lightweight Architectural Decisions

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/Alert/Alert.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/utils/missingInformation.ts, src/Hedwig/Data/DbInitializer.cs
right now this simply adds the alert icons to the roster view, @victoriasuwardiman do we need to impl such that when a user goes in to update the data, the icon then goes away? or do we just want reaction to the icons in the roster?
also -- the legend looks less than great with my changes from this branch and https://github.com/ctoec/ecis-experimental/pull/368, someone please help :)
also closes #365  roster sorting cleanup
links #307
=> Fake incomplete data

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/hooks/useApi.ts
Clean the API of useApi hook. Affects some current oustanding PRs.
=> Replace positions args in useApi to ops obj

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/utils/currencyFormatter.ts, src/Hedwig/ClientApp/src/utils/notNullOrUndefined.ts, src/Hedwig/ClientApp/src/utils/parseCurrencyFromString.ts
Quick PR:
* Updates report layout to match designs, with accredited above the utilization table. Also updates the utilization table with the unsaved value of accredited.
* Fixes for currency fields when equal to 0.
=> Update report layout

src/Hedwig/ClientApp/public/index.html, src/Hedwig/ClientApp/public/manifest.json, src/Hedwig/ClientApp/src/containers/App/App.tsx
=> Change the name to ECE Reporter

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/yarn.lock
=> Update uswds to fix icon

src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss
We can also go to `0.5` if we want them tighter.
PR URL: https://18.189.31.19:5001
Should close #396
=> Decrease leading from 2 to 1

src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss
Should close #395
URL: https://18.216.99.184:5001
=> Change color and make bold

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/generated/models/Child.ts, src/Hedwig/Migrations/20191213153356_ChangeHispanicOrLatinxEthnicityToNullableOnChild.Designer.cs, src/Hedwig/Migrations/20191213153356_ChangeHispanicOrLatinxEthnicityToNullableOnChild.cs, src/Hedwig/Models/Child.cs, src/Hedwig/Models/Reports/CdcReport.cs
=> Make hispanic/latinx nullable

entrypoint-test.sh, src/Hedwig/Data/HedwigContext.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/HedwigRepository.cs, test/HedwigTests/Data/HedwigContextTests.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs
=> 434: AuthorId added to entire temporal entity object tree

src/Hedwig/ClientApp/src/assets/styles/print.scss, src/Hedwig/ClientApp/src/components/Button/Button.tsx, src/Hedwig/ClientApp/src/containers/ReportDetail/ReportDetail.tsx
Should close #283 
URL: https://3.134.245.10:5001
=> Add print to report detail

src/Hedwig/Data/DbInitializer.cs
(Previous PR was merged into an already closed branch.)
=> Honey pot data

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss, src/Hedwig/ClientApp/src/components/Checklist/Checklist.stories.tsx, src/Hedwig/ClientApp/src/components/Checklist/Checklist.tsx, src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.stories.tsx, src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx, src/Hedwig/ClientApp/src/components/RadioGroup/RadioGroup.stories.tsx, src/Hedwig/ClientApp/src/components/RadioGroup/RadioGroup.tsx, src/Hedwig/ClientApp/src/components/TextInput/TextInput.stories.tsx, src/Hedwig/ClientApp/src/components/TextInput/TextInput.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/utils/models/child.ts, src/Hedwig/ClientApp/src/utils/models/family.ts, src/Hedwig/ClientApp/src/utils/models/index.ts, src/Hedwig/ClientApp/src/utils/validations/hasValidationErrors.ts, src/Hedwig/ClientApp/src/utils/validations/processValidationError.ts, src/Hedwig/ClientApp/src/utils/validations/sectionHasValidationErrors.ts, src/Hedwig/ServiceExtensions.cs, src/Hedwig/Validations/Rules/Child/BirthStateRequired.cs, src/Hedwig/Validations/Rules/Child/BirthTownRequired.cs, test/HedwigTests/Validations/Rules/Child/BirthStateRequiredTests.cs, test/HedwigTests/Validations/Rules/Child/BirthTownRequiredTests.cs
addresses #427  but does not address Enrollment/Funding section yet
also:
closes #451 
closes #461 
PR env link: https://18.217.201.58:5001/
=> 427 validation errors inline

src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Repositories/EnrollmentRepository.cs
Prereq and placeholder for ui update
=> Add reporting period include and update db init

src/Hedwig/ClientApp/src/components/StepList/Step.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx
Should close #155.
I wasn't 100% clear what the requirements were because of conflicts comments/comps in the issue discussion. Let me know if anything needs to change on this PR.
URL: https://18.223.188.88:5001
=> Skip family income for foster

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx
=> Swap missing info and edit links in enrollment detail

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx
=> Only private pay with income not disclosed

src/Hedwig/ServiceExtensions.cs, src/Hedwig/Validations/Rules/Enrollment/StartDateIsBeforeEndOfFirstReportingPeriod.cs, test/HedwigTests/Validations/Rules/Enrollment/StartDateIsBeforeEndOfFirstReportingPeriodTests.cs
Backend for #470.
Frontend in separate PR.
=> Add backend validation for entry start date

src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/utils/cartesianProduct.tsx
No more tests than before, but more testable functions!
=> Incomplete report detail refactor

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/utils/models/family.ts
=> 528: Fixes error when attempting to view incomplete enrollment

src/Hedwig/Program.cs, src/Hedwig/Startup.cs
@speedcm -- do we plan to use "Development" as the environment for staging?
=> No dbinit in non-dev

src/Hedwig/ClientApp/src/components/DatePicker/DatePicker.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx
Solution: check if value is null OR undefined
issue with that: it should always be null. weird.
additional rider: Add missing info styling to birth date
=> 542: A hacky fix for ethnicity selection

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/generated/models/ValidationError.ts, src/Hedwig/ClientApp/src/utils/validations/hasValidationErrors.ts, src/Hedwig/ClientApp/src/utils/validations/sectionHasValidationErrors.ts, src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Validations/Rules/Child/FamilyIdRequired.cs, src/Hedwig/Validations/Rules/Child/FamilyIsValid.cs, src/Hedwig/Validations/Rules/Enrollment/ChildIsValid.cs, src/Hedwig/Validations/Rules/Family/MostRecentDeterminationIsValid.cs, src/Hedwig/Validations/Rules/FieldRequired.cs, src/Hedwig/Validations/Rules/Report/Cdc/EnrollmentsAreValid.cs, src/Hedwig/Validations/ValidationError.cs, test/HedwigTests/Validations/Rules/Child/FamilyIsValidTests.cs, test/HedwigTests/Validations/Rules/ConditionalFieldRequiredTests.cs, test/HedwigTests/Validations/Rules/Enrollment/ChildIsValidTests.cs, test/HedwigTests/Validations/Rules/Enrollment/FundingIsValidTests.cs, test/HedwigTests/Validations/Rules/Family/MostRecentDeterminationIsValidTest.cs, test/HedwigTests/Validations/Rules/FieldRequiredTests.cs, test/HedwigTests/Validations/Rules/Report/Cdc/EnrollmentsAreValidTests.cs, test/HedwigTests/Validations/ValidatorTests.cs
=> 531 section 1 incomplete

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss, src/Hedwig/ClientApp/src/components/Checklist/Checklist.tsx, src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx, src/Hedwig/ClientApp/src/components/FormStatus/FormStatus.tsx, src/Hedwig/ClientApp/src/components/RadioGroup/RadioGroup.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/splitCamelCase.ts
Fixes QA list issues identified in #544 and generally corrects spacing for components that use fieldset.
There's still some screwiness with fieldset child input error spacing but I figure it's better to fix most of the things and make a new ticket for that.
=> 544 spacing styling fixes

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/utils/validations/processBlockingValidationErrors.ts
This addresses all of the funding related issues in the QA list.
Working on identifying tickets. So far, should close #470, should close #571 
URL:...
=> Funding fixes

src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/models/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/index.ts, src/Hedwig/ClientApp/src/utils/types.ts, src/Hedwig/appsettings.json
also, removes references to tsFilter and tsFilter method
also, adds dev values for logging in appsettings.json
=> 574: Aligns roster counts with report counts of enrollments missing info

src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx
=> Style tweaks

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts, src/Hedwig/ClientApp/yarn.lock
I have no way of testing this in safari and am not sure it will resolve the issue :/
=> Browser diff date debug

src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/enrollmentTypes.tsx, src/Hedwig/ClientApp/src/utils/models/funding.ts
Issue: Errors don't show up when trying to hit save on ChildInfo when first and last name are blank
Rider: Funding space formatting when not specified on roster
=> Fix delayed errors

installer/tf/prsystem/startup.sh
Because we no longer use it in WingedKeys
=> Change appsettings.Development to appsettings

src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/generated/apis/HedwigApi.ts, src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Data/HedwigContext.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, test/HedwigTests/Controllers/EnrollmentsControllerTests.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs
Should close #158 
PR URL: https://18.220.0.248:5001
I added an alert after successfully cancelling, but we can remove that if not desired.
=> Add cancel enrollment functionality

src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Controllers/OrganizationsController.cs, src/Hedwig/Controllers/ReportingPeriodController.cs, src/Hedwig/Controllers/SitesController.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/OrganizationRepository.cs, src/Hedwig/Repositories/ReportingPeriodRepository.cs, src/Hedwig/Repositories/UserRepository.cs, src/Hedwig/Security/RequirementsHandler.cs
Rider: clean up unnecessary using statements
=> Remove uncessary async keyword

src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/components/InlineIcon/InlineIcon.tsx, src/Hedwig/ClientApp/src/components/Table/ColumnHeader.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/ReportsSummary.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/contexts/Alert/AlertContext.tsx, src/Hedwig/ClientApp/src/contexts/Authentication/AuthenticationContext.tsx, src/Hedwig/ClientApp/src/hooks/useApi.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.ts, src/Hedwig/ClientApp/src/utils/validations/errorForField.ts, src/Hedwig/ClientApp/src/utils/validations/processBlockingValidationErrors.ts
Remove almost all react warnings
Left `Dropdown` warnings b/c @mmazanec22 has an open PR that removes that file.
A warning about a deps list in `useFocusFirstError` that I didn't look too hard into how to solve.
Should close #613
=> React clean up

src/Hedwig/ClientApp/src/components/DatePicker/DatePicker.tsx
=> Default datepicker to startdate

src/Hedwig/Migrations/20200116141931_AddIdsToSite.Designer.cs, src/Hedwig/Migrations/20200116141931_AddIdsToSite.cs, src/Hedwig/Models/Site.cs
These are IDs used in other systems including ECIS, Directory Manager, and Registry, as well as miscellaneous spreadsheets.
=> Add additional ids for linking Site to other data sources

src/Hedwig/Models/Child.cs, src/Hedwig/Models/Enrollment.cs, src/Hedwig/Models/Family.cs, src/Hedwig/Models/FamilyDetermination.cs, src/Hedwig/Models/Funding.cs, src/Hedwig/Models/FundingSpace.cs, src/Hedwig/Models/HedwigIdEntity.cs, src/Hedwig/Models/Organization.cs, src/Hedwig/Models/Permissions/Permission.cs, src/Hedwig/Models/ReportingPeriod.cs, src/Hedwig/Models/Reports/Report.cs, src/Hedwig/Models/Site.cs, src/Hedwig/Models/User.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/HedwigRepository.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs
=> Abstract enumerable child object update

src/Hedwig/ClientApp/src/components/DatePicker/DatePicker.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/utils/enrollmentTextFormatter.ts, src/Hedwig/ClientApp/src/utils/models/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts
where should I be creating unit tests for util functions?
closes #620
=> 620 funding current to enrollment

azure-pipelines.yml, installer/iis/web.config
As a member of the DevOps team, I must be able to enable or disable logging at the environment level.
The Azure DevOps Release pipelines must allow the web.config property, stdoutLogEnabled, to be set for any environment (e.g. staging, uat, prod). The values for this property are either “true” or “false”.
-----------------------------
During the release pipeline execution, the published files are packaged and then deployed. A packaging task copies the web.config file from installer\iis to the zip root.
To support tokenization, the web.config file was updated to have a token for the stdoutLogEnabled attribute. This token is called StdoutLogEnabled.
To replace this token during execution of the release pipeline, the following was done (tested in UAT):
* a new market place task, Tokenizer, …
=> added token for web.config stdoutLogEnabled (#633)

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/utils/models/child.ts, src/Hedwig/ClientApp/src/utils/models/enrollment.test.ts, src/Hedwig/ClientApp/src/utils/models/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.test.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.ts, src/Hedwig/ClientApp/src/utils/models/funding.test.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.test.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts
=> 634: Starts adding more tests for utils

src/Hedwig/Validations/NonBlockingValidator.cs, src/Hedwig/Validations/Rules/Family/MostRecentDeterminationIsValid.cs, test/HedwigTests/Validations/Rules/Family/MostRecentDeterminationIsValidTest.cs, test/HedwigTests/Validations/ValidatorTests.cs
=> 644: Skip family determination validation if Child.Foster = true

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/cartesianProduct.test.tsx, src/Hedwig/ClientApp/src/utils/fundingSelectionUtils.ts, src/Hedwig/ClientApp/src/utils/models/ageGroup.test.ts, src/Hedwig/ClientApp/src/utils/models/ageGroup.ts, src/Hedwig/ClientApp/src/utils/models/fundingTime.ts, src/Hedwig/ClientApp/src/utils/models/index.ts
=> 634-age-group-util-tests

src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss
=> Add bottom margin to app and note to revisit

src/Hedwig/ClientApp/src/assets/styles/_uswds-theme-custom-styles.scss
=> Remove extra margin from H1

src/Hedwig/Data/DbInitializer.cs, src/Hedwig/HostedServices/CDCReportGeneratorScopedService.cs, src/Hedwig/HostedServices/CdcReportGeneratorScopedService.cs, src/Hedwig/HostedServices/DailyServiceExecutor.cs, src/Hedwig/Repositories/OrganizationRepository.cs, src/Hedwig/Repositories/ReportRepository.cs, src/Hedwig/ServiceExtensions.cs, src/Hedwig/Startup.cs, src/Hedwig/Utilities/IDateTime.cs, src/Hedwig/Utilities/SystemDateTime.cs, test/HedwigTests/Helpers/FundingSpaceHelper.cs, test/HedwigTests/Helpers/OrganizationHelper.cs, test/HedwigTests/HostedServices/CdcReportGeneratorScopedServiceTests.cs
Should resolve #363
Co-authored-by: jlhogan <julia@skylight.digital>
=> Add automatic report generation with hosted services

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx
=> 671: Removes extra -Select- option from gender drop down

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/utils/fundingSelectionUtils.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts, src/Hedwig/ClientApp/yarn.lock, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/HedwigRepository.cs, src/Hedwig/Repositories/SiteRepository.cs
=> 429 alert overutilization

src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/hooks/onRouteChange.ts, src/Hedwig/ClientApp/src/hooks/useRouteChange.ts
=> On route change in new enrollment, scroll to top

src/Hedwig/Migrations/20200204171519_ConvertDateTimeToDate.Designer.cs, src/Hedwig/Migrations/20200204171519_ConvertDateTimeToDate.cs, src/Hedwig/Models/Child.cs, src/Hedwig/Models/Enrollment.cs, src/Hedwig/Models/FamilyDetermination.cs, src/Hedwig/Models/Funding.cs, src/Hedwig/Models/ReportingPeriod.cs
=> 698: Convert DateTime columns to Date where appropriate

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.test.tsx
Wow this is so much cleaner, and I love that the snapshots are readable!
=> Convert enrollment tests to react testing library

.devcontainer/backend/.devcontainer.json, test/HedwigTests/Data/HedwigContextTests.cs
I don't know if this has always been like this, but I just tried restarting VS code and it broke. This change fixed it.
=> Fix dev container

src/Hedwig/ClientApp/src/containers/App/App.test.tsx, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
=> Convert App tests

src/Hedwig/Data/HedwigContext.cs, src/Hedwig/Migrations/20200130155633_AddUpdatedAtToTemporalEntities.Designer.cs, src/Hedwig/Migrations/20200130155633_AddUpdatedAtToTemporalEntities.cs, src/Hedwig/Models/Attributes/ReadOnlyAttribute.cs, src/Hedwig/Models/TemporalEntity.cs, test/HedwigTests/Data/HedwigContextTests.cs, test/HedwigTests/Helpers/FamilyHelper.cs, test/HedwigTests/Models/TemporalEntityTests.cs
=> 661: Adds UpdatedAt to temporal entities

src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/components/Header/_index.scss, src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap, src/Hedwig/ClientApp/src/containers/PrivacyPolicy/PrivacyPolicy.test.tsx, src/Hedwig/ClientApp/src/containers/PrivacyPolicy/PrivacyPolicy.tsx, src/Hedwig/ClientApp/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, src/Hedwig/ClientApp/src/routes.ts
=> Add privacy policy (#716)

src/Hedwig/ClientApp/src/components/StepList/StepList.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/contexts/__mocks__/CommonContextProviderMock.tsx, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts, src/Hedwig/ClientApp/src/setupTests.ts
Should close #737 
Added a test for regression catching (which took way too long to add smh)
Bug was introduced in #603
=> Fix foster skipping and add test

src/Hedwig/Data/DbInitializer.cs
=> 709: Fix invalid seed data

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/generated/models/Child.ts, src/Hedwig/ClientApp/src/generated/models/Enrollment.ts, src/Hedwig/ClientApp/src/generated/models/Family.ts, src/Hedwig/ClientApp/src/generated/models/FamilyDetermination.ts, src/Hedwig/ClientApp/src/generated/models/Funding.ts, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts, src/Hedwig/ClientApp/src/utils/stringFormatters/enrollmentDetailMetadataFormatter.ts, src/Hedwig/ClientApp/src/utils/stringFormatters/index.ts, src/Hedwig/ClientApp/src/utils/stringFormatters/rosterEnrollmentsFormatter.ts, src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Repositories/EnrollmentRepository.cs
closes #734 
from local dev env after change:
=> 734 enrollment update metadata

src/Hedwig/ClientApp/src/components/Alert/Alert.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx, src/Hedwig/ClientApp/src/utils/stringFormatters/index.ts
=> 720 alert copy changes

src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/generated/apis/HedwigApi.ts, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/Controllers/ChildrenController.cs, src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Repositories/ChildRepository.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/HedwigRepository.cs, src/Hedwig/Security/SiteAccess/NoSiteSpecifiedAccessHandler.cs, src/Hedwig/ServiceExtensions.cs, test/HedwigTests/Repositories/ChildRepositoryTests.cs
Should close #444 
Let me know if this is the desired functionality
=> Add c4k count to report

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/Header/Header.tsx, src/Hedwig/ClientApp/src/components/Header/_index.scss, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
=> Ditch unnecessary em tag and extend link focus style to logo text

src/Hedwig/ClientApp/src/components/Table/Table.tsx, src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/Hedwig/Data/DbInitializer.cs
=> Add site column

src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx
=> Prevent withdraw for missing info

src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
=> Revert nav bar title to Roster

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx
=> Hide when over utilization alert no longer applies

src/Hedwig/Data/DbInitializer.cs
@cailyncodes Since you're working on multi-site things, these names roughly match the length of Mt. Olive, and are more likely to trip any width-based problems.
=> Update seed data names with more realistic lengths

src/Hedwig/ClientApp/src/containers/Roster/RosterHeader.tsx
=> Add roster header guard for single site

src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDropdown.module.scss, src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDrowdown.tsx, src/Hedwig/ClientApp/src/components/InlineIcon/InlineIcon.tsx, src/Hedwig/ClientApp/src/containers/Roster/RosterHeader.tsx
=> Add an enroll button for multisite program roster

src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDropdown.module.scss
=> Expand dropdown option to full width

src/Hedwig/ClientApp/report.20200227.203837.4842.0.001.json, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts
=> Fix missing info that was over zealous and dropdown bugs on income not disclosed

src/Hedwig/ClientApp/src/components/StepList/_index.scss, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx
=> Remove site dropdown

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/Header/Header.tsx, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
Should close #815
My oops when I merged in that most recent PR
=> Fix header

src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
Fix funding space on roster
Should close #831
=> Fix funding space

src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx
=> Update withdrawal screen to use consistent formatting of reporting periods

src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Controllers/ReportsController.cs, src/Hedwig/Filters/TransformEntityFilterAttribute.cs, src/Hedwig/Models/Attributes/ReadOnlyAttribute.cs, src/Hedwig/Models/Enrollment.cs
=> 827: Transform api responses with ActionFilter

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceList.tsx, src/Hedwig/ClientApp/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap, src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/hooks/usePromiseExecution.ts, src/Hedwig/ClientApp/src/hooks/useRouteChange.ts, src/Hedwig/ClientApp/src/utils/forms/form.ts, src/Hedwig/ClientApp/src/utils/models/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/family.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts
Converted report, withdrawal, and most of enrollment flow.  IMO refactoring funding and updateData and making a form component make sense as a separate PR.
=> Use form reducer

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/ReportsSummary.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx, src/Hedwig/ClientApp/src/tests/data/enrollment.ts, src/Hedwig/ClientApp/src/tests/data/organization.ts, src/Hedwig/ClientApp/src/tests/data/report.ts, src/Hedwig/ClientApp/src/tests/data/site.ts
=> 731 roster tests

src/Hedwig/Validations/Rules/Family/MostRecentDeterminationIsValid.cs, test/HedwigTests/Validations/Rules/Family/MostRecentDeterminationIsValidTest.cs
todo: figure out how to test validations work in the full chain as they're actually executed by the controllers
=> Fix broken validation after context refactor

src/Hedwig/ClientApp/src/contexts/Authentication/AuthenticationContext.tsx, src/Hedwig/ClientApp/src/index.tsx, src/Hedwig/Validations/Rules/Family/MostRecentDeterminationIsValid.cs, test/HedwigTests/Validations/Rules/Family/MostRecentDeterminationIsValidTest.cs
=> Add id token to localstorage for peristence

.gitignore, src/Hedwig/ClientApp/package.json
=> Update storybook build output directory

src/Hedwig/Filters/TransformEntityFilterAttribute.cs
fixes the report bug, and the issue we had with the withdrawal page
=> Reset read-only properties for POST/PUT responses

docker-compose.yaml, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/e2e/QueryHelper.ts, src/Hedwig/ClientApp/src/e2e/environment_values.json, src/Hedwig/ClientApp/src/e2e/tests/App.e2e.test.ts, src/Hedwig/ClientApp/src/e2e/tests/Enroll.e2e.test.ts, src/Hedwig/ClientApp/src/e2e/utilities/enroll.ts, src/Hedwig/ClientApp/src/e2e/utilities/login.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts
=> Enrollment tests

src/Hedwig/Filters/TransformEntityFilterAttribute.cs, src/Hedwig/Repositories/EnrollmentRepository.cs
Brings back author reference on temporal entities, which brings back the enrollment update metadata infomation on enrollment detail view
=> Add back in author reference on enrollment

src/Hedwig/ServiceExtensions.cs
sorry I forgot to put this up last night !
=> Temporarily disable 1 year requirement for family validations right now

.gitignore, src/Hedwig/ClientApp/src/tests/helpers.ts, src/Hedwig/Controllers/EnrollmentsController.cs, src/Hedwig/Controllers/ReportsController.cs, src/Hedwig/Filters/TransformEntityFilterAttribute.cs, src/Hedwig/Filters/TypeExtensions.cs, src/Hedwig/Filters/ValidateEntityFilterAttribute.cs, src/Hedwig/ServiceExtensions.cs, src/Hedwig/Validations/NonBlockingValidator.cs, test/HedwigTests/Controllers/EnrollmentsControllerTests.cs, test/HedwigTests/Controllers/ReportsControllerTests.cs, test/HedwigTests/Filters/TestApplicationModel.cs, test/HedwigTests/Filters/TypeExtensionsTests.cs, test/HedwigTests/Filters/ValidateEntityFilterAttributeTests.cs, test/HedwigTests/Fixtures/Migrations/99999999999999_BootstrapTestData.Designer.cs, test/HedwigTests/Fixtures/Migrations/99999999999999_BootstrapTestData.cs
=> 875 validation action filter

src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap
=> Remove optional tag from c4k revenue in report submit

src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.test.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/__snapshots__/Withdrawal.test.tsx.snap, src/Hedwig/ClientApp/src/utils/fundingTypeFormatters.tsx, src/Hedwig/ClientApp/src/utils/models/funding.ts
=> 872 fix withdrawal regressions

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/components/ProcessList/ProcessList.stories.tsx, src/Hedwig/ClientApp/src/components/ProcessList/ProcessList.tsx, src/Hedwig/ClientApp/src/components/ProcessList/ProcessStep.tsx, src/Hedwig/ClientApp/src/components/ProcessList/_index.scss, src/Hedwig/ClientApp/src/components/_index.scss, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/utils/dateFormatter.ts, src/Hedwig/ClientApp/src/utils/dateSorter.ts, src/Hedwig/ClientApp/src/utils/models/c4kCertificate.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/enrollment.test.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/history.test.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/history.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/index.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.test.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.test.ts
Also:
- Adds ProcessList component
- Adds dateSorter util and refactors model util sorts to use it
- Extends dateFormatter to optionally produce a 'long' style format
('MMMM Do, YYYY')
PR env link: https://13.58.19.253:5001/
=> 735: Add enrollment history to enrollment detail view

src/Hedwig/ClientApp/src/generated/models/C4KCertificate.ts, src/Hedwig/ClientApp/src/generated/models/Funding.ts, src/Hedwig/ClientApp/src/generated/models/FundingSpace.ts, src/Hedwig/Filters/TransformEntityFilterAttribute.cs, src/Hedwig/Filters/ValidateEntityFilterAttribute.cs, src/Hedwig/Migrations/20200401021838_UpdateFundingAddFundingSpace.Designer.cs, src/Hedwig/Migrations/20200401021838_UpdateFundingAddFundingSpace.cs, src/Hedwig/Models/Funding.cs, src/Hedwig/Models/FundingSpace.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Validations/Rules/Funding/FundingTimelinesAreValid.cs
part one (next pr to remove time & make FE changes coming soon!) 
includes rider fix to avoid null reference exception on 404 responses in action filters 
relates to #858
=> 858: Add FundingSpace to Funding

src/Hedwig/ClientApp/src/components/ProcessList/ProcessList.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/generated/models/Funding.ts, src/Hedwig/ClientApp/src/tests/data/enrollment.ts, src/Hedwig/ClientApp/src/utils/fundingType.test.ts, src/Hedwig/ClientApp/src/utils/fundingType.tsx, src/Hedwig/ClientApp/src/utils/models/c4kCertificate.test.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/enrollment.test.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/enrollment/history.ts, src/Hedwig/ClientApp/src/utils/models/funding.test.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/ClientApp/src/utils/models/fundingSpace.ts, src/Hedwig/ClientApp/src/utils/models/index.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.test.ts, src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Migrations/20200401210141_UpdateFundingRemoveTime.Designer.cs, src/Hedwig/Migrations/20200401210141_UpdateFundingRemoveTime.cs, src/Hedwig/Models/Funding.cs, src/Hedwig/Validations/Rules/Funding/FundingTimelinesAreValid.cs, test/HedwigTests/Helpers/FundingHelper.cs, test/HedwigTests/Repositories/ReportRepositoryTests.cs
part II, closes #858 
NOTE: Validations still needed, but want to make sure the actual requirements are captured before I just go writing them, so going to leave that to a separate ticket/task
=> 858 funding remove time

src/Hedwig/ClientApp/src/hooks/useApi.ts, src/Hedwig/Controllers/EnrollmentsController.cs
=> 918: Fix cancel flow

src/Hedwig/Repositories/ReportRepository.cs
unblocks 933, but leaving that open for a more in depth discussion & solution
=> 933: Quick fix - unblock report submission

azure-pipelines.yml, src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceList.stories.tsx, src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceList.test.tsx, src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceList.tsx, src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceListExpansion.tsx, src/Hedwig/ClientApp/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap, src/Hedwig/ClientApp/src/components/ChoiceList/_index.scss, src/Hedwig/ClientApp/src/components/_index.scss, src/Hedwig/ClientApp/src/components/index.ts, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/__snapshots__/EnrollmentEdit.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx, src/Hedwig/ClientApp/src/tests/data/enrollment.ts, src/Hedwig/ClientApp/src/tests/data/organization.ts, src/Hedwig/ClientApp/src/tests/data/report.ts, src/Hedwig/ClientApp/src/tests/data/site.ts
Should close #890 
PR URL: https://18.220.9.99:5001
=> Add expandable choicelist and update enrollment funding to use it

src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceList.tsx
Maybe will close #948. Who knows? We'll need to test this in staging RIP
=> Change ChoiceListExpansion name check

src/Hedwig/ClientApp/src/hooks/useApi.ts
Fix the past enrollments explosion bug
=> Fix reset on params change

src/Hedwig/ClientApp/src/generated/models/Child.ts, src/Hedwig/Migrations/20200413181724_UpdateC4KCertificatesOnChild.Designer.cs, src/Hedwig/Migrations/20200413181724_UpdateC4KCertificatesOnChild.cs, src/Hedwig/Models/Child/Child.cs
=> Remove required annotation on c4kcerts

src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/__snapshots__/EnrollmentEdit.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/EntryForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Summary.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/UpdateForm.tsx, src/Hedwig/ClientApp/src/utils/dateFilter.test.ts, src/Hedwig/ClientApp/src/utils/dateFilter.ts, src/Hedwig/ClientApp/src/utils/dateSorter.test.ts, src/Hedwig/ClientApp/src/utils/dateSorter.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.test.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.test.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts
=> Change reporting period dropdown options

src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/UtilizationTable.test.tsx.snap, src/Hedwig/ClientApp/src/utils/currencyFormatter.ts, src/Hedwig/ClientApp/src/utils/notNullOrUndefined.ts
=> Currency formatting in utilization table

src/Hedwig/ClientApp/src/generated/models/Child.ts, src/Hedwig/ClientApp/src/generated/models/Enrollment.ts, src/Hedwig/ClientApp/src/generated/models/Family.ts, src/Hedwig/ClientApp/src/generated/models/FamilyDetermination.ts, src/Hedwig/ClientApp/src/generated/models/Funding.ts, src/Hedwig/ClientApp/src/generated/models/FundingTimeAllocation.ts, src/Hedwig/ServiceExtensions.cs
Looks like the API generator also hasn't been run in a while
=> Remove DescribeEnumsAsString

src/Hedwig/Models/Reports/Report.cs, test/HedwigTests/Integrations/EnrollmentsControllerIntegrationTests.cs, test/HedwigTests/Integrations/HedwigAPIRequests.cs, test/HedwigTests/Integrations/OrganizationsConrollerIntegrationTests.cs, test/HedwigTests/Integrations/ReportsControllerIntegrationTests.cs
=> Add remaining GET tests

test/HedwigTests/Integrations/EnrollmentsControllerIntegrationTests.cs, test/HedwigTests/Integrations/HedwigAPIRequests.cs
=> Add enrollment post test

src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx
=> Remove extra withdraw alert message

src/Hedwig/ClientApp/src/components/Card/Card.tsx, src/Hedwig/ClientApp/src/components/Card/CardExpansion.tsx
Should close #985
Fix react build rename
=> Don't auto expand family deterimination card in staging

src/Hedwig/Configuration/AppExtensions.cs, src/Hedwig/Configuration/EnvironmentConfiguration.cs, src/Hedwig/Configuration/ServiceExtensions.cs, src/Hedwig/Migrations/HedwigContextModelSnapshot.cs, src/Hedwig/Program.cs, src/Hedwig/Startup.cs, src/Hedwig/appsettings.json, test/HedwigTests/Fixtures/TestHedwigContextProvider.cs, test/HedwigTests/Fixtures/TestStartup.cs
Adds the `AutomaticallyApplyMigrations` appsettings variable
Should close #833
=> Add automatic migation guard

src/Hedwig/Models/Enrollment/EnrollmentProfile.cs
Should close #993 and close #999
=> Fix entry/exit typo

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/EntryForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Summary.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/UpdateForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/utils/models/enrollment/history.ts, src/Hedwig/ClientApp/src/utils/models/family.ts
=> Add guard for very incomplete enrollments

src/Hedwig/ClientApp/src/containers/App/App.tsx
=> Use cache invalidator

src/Hedwig/ClientApp/src/generated/models/C4KCertificate.ts, src/Hedwig/Configuration/ServiceExtensions.cs, src/Hedwig/Models/C4KCertificate/C4KCertificate.cs, src/Hedwig/Models/C4KCertificate/C4KCertificateProfile.cs, src/Hedwig/Models/C4KCertificate/C4kCertificateDTO.cs, src/Hedwig/Models/Child/EnrollmentChildDTO.cs, src/Hedwig/Models/Child/EnrollmentSummaryChildDTO.cs
=> Add child to c4kcert model

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/Configuration/AppExtensions.cs, src/Hedwig/Program.cs, src/Hedwig/appsettings.json
Should close #1012 
AutomaticallyApplyMigrations has become "Database:AutomaticallyApplyMigrations"
Adds 'Database:SeedData"
=> Add seed database guard

src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/components/Table/ColumnHeader.tsx, src/Hedwig/ClientApp/src/components/Table/Table.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/UtilizationTable.test.tsx.snap
Should close #987 
PR URL: https://18.221.73.211:5001
=> Right align report number cols and update invisible padding

src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx
=> Truncate site column in roster

azure-pipelines.yml
azure pipeline validation check
=> azure pipeline validation check

src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/e2e/tests/Enroll.e2e.test.ts
Should close #995
Include a missing useEffect dependency
Add more comments
Update reporting period options variable names and ensure we look far enough into the future
Use periodEnd as opposed to periodStart to include the current reporting period as an option
Open question on some code -- see inline comments
=> Include missing useEffect dep to fix contract select

src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/Hedwig/ClientApp/src/utils/fundingType.tsx, src/Hedwig/ClientApp/src/utils/models/c4kCertificate.ts, src/Hedwig/Data/DbInitializer.cs
=> Show only needed info in tags

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/legendFormatters.tsx, src/Hedwig/ClientApp/src/utils/models/c4kCertificate.ts
=> 1021: Updates current c4k cert logic to rely on unset end date

src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/EntryForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/enrollmentTypes.tsx
=> Restructure visit callback

src/Hedwig/Configuration/EnvironmentConfiguration.cs, src/Hedwig/Configuration/ServiceExtensions.cs, src/Hedwig/Controllers/ReportingPeriodsController.cs, src/Hedwig/Program.cs, src/Hedwig/Repositories/ReportingPeriodRepository.cs, src/Hedwig/Startup.cs, test/HedwigTests/Controllers/ReportingPeriodsControllerTests.cs, test/HedwigTests/Data/HedwigContextTests.cs, test/HedwigTests/Fixtures/TestStartup.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs, test/HedwigTests/Repositories/FamilyDeterminationRepositoryTests.cs, test/HedwigTests/Repositories/FamilyRepositoryTests.cs, test/HedwigTests/Repositories/FundingRepositoryTests.cs, test/HedwigTests/Repositories/HedwigRepositoryTests.cs, test/HedwigTests/Repositories/OrganizationRepositoryTests.cs, test/HedwigTests/Repositories/ReportingPeriodRepositoryTests.cs, test/HedwigTests/Repositories/UserRepositoryTests.cs, test/HedwigTests/Security/SiteAccess/MultipleSiteAccessHandlerTests.cs, test/HedwigTests/Security/SiteAccess/SingleSiteAccessHandlerTests.cs
I'm about to create a ticket that documents findings re testing and touch points between application areas.
=> Misc refactor and mild test clean up

src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx
=> 1048 withdrawal site name

src/Hedwig/ClientApp/src/utils/models/family.ts
=> Fix address formatter

src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/App/MakeRouteWithSubRoutes.tsx, src/Hedwig/ClientApp/src/containers/NotSignedInRedirect/NotSignedInRedirect.tsx, src/Hedwig/ClientApp/src/routes.ts
=> Add not signed in redirect guard

src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/components/DirectionalLink/_index.scss, src/Hedwig/ClientApp/src/containers/CommonContainer.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/__snapshots__/ReportsSummary.test.tsx.snap
=> Remove margin from directional link

src/Hedwig/ClientApp/src/components/Form_New/FormField.tsx, src/Hedwig/ClientApp/src/components/Form_New/ObjectDriller.ts, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx
Adds the missing types that got skipped in a PR merge
=> Fix typings

src/Hedwig/ClientApp/src/components/Form_New/Form.tsx, src/Hedwig/ClientApp/src/components/Form_New/FormContext.ts, src/Hedwig/ClientApp/src/components/Form_New/ObjectDriller.ts
Also, change ObjectDriller constructor to use data object,
instead of copy.
=> FormContext gets ObjectDriller instance

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/DateInput/DateInput.stories.tsx, src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/components/DateRangeInput/DateRangeInput.tsx, src/Hedwig/ClientApp/src/components/Form/FormField.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/__snapshots__/EnrollmentEdit.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/RosterHeader.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/__snapshots__/Withdrawal.test.tsx.snap
Previous onChange instances were changed to onChange_Old and the new system is just onChange now.
=> Add date native event handler

src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
=> Fix padding on homepage

src/Hedwig/ClientApp/src/components/Checkbox/Checkbox.tsx, src/Hedwig/ClientApp/src/components/Form_New/Form.tsx, src/Hedwig/ClientApp/src/components/Form_New/FormField.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Update/__snapshots__/EnrollmentUpdate.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/NewForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/NewForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/Accredited.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/C4KRevenue.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/Comment.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/FamilyFeesRevenue.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/OtherRevenueFieldSet.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/RetroactiveC4KRevenue.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/TimeSplitUtilizationField.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitFields/index.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/UtilizationTable.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/__snapshots__/Withdrawal.test.tsx.snap, src/Hedwig/ClientApp/src/utils/dateFilter.ts, src/Hedwig/ClientApp/src/utils/models/fundingSpace.ts, src/Hedwig/ClientApp/src/utils/models/fundingTimeSplitUtilization.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx
Should close #1135 
My self review will come later tonight or tomorrow morning. Feel free to hold off reviewing until then
=> Refactor report submit form

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/components/DateInput/_index.scss, src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Update/__snapshots__/EnrollmentUpdate.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Withdrawal/__snapshots__/Withdrawal.test.tsx.snap
=> Dateinput today warning

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/Summary.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/utils/models/child.ts
Should close #532 
Rider: The comps in #532 have `Date of Birth` instead of `Birthdate`
=> Add birth certificate id to summary

src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap
=> Add site name to enrollment new

installer/tf/prsystem/startup.sh
=> fix docker os watchers limit (#1153)

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/images/downArrowCircle.svg, src/Hedwig/ClientApp/src/components/Table/ColumnHeader.tsx, src/Hedwig/ClientApp/src/components/Table/_index.scss, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/UtilizationTable.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/__snapshots__/ReportsSummary.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/Hedwig/ClientApp/src/storyshots.test.ts
Closes #1046 with slight modification after conversation with @RyanHansz .
=> 1046 obvious sorting

src/Hedwig/ClientApp/src/components/DateInput/_index.scss
I must have messed up the layout in my recent PR-- here's a fix (also ran prettier, sorry for random spacing change)
=> Fix datepicker layout, update snapshots

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/TabNav/TabNav.stories.tsx, src/Hedwig/ClientApp/src/components/TabNav/TabNav.tsx, src/Hedwig/ClientApp/src/components/TabNav/_index.scss, src/Hedwig/ClientApp/src/components/_index.scss, src/Hedwig/ClientApp/src/containers/Test/Test.tsx, src/Hedwig/ClientApp/src/routes.ts
Should close #1146 
Will remove `Test` after review
=> Add tab nav with example

src/Hedwig/Models/FamilyDetermination/EnrollmentFamilyDeterminationDTO.cs
Not related to a Task - discussed issue over email.
=> Remove NotDisclosed from EnrollmentFamilyDeterminationDTO

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/NewForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/UpdateForm/Care4Kids/index.tsx, src/Hedwig/ClientApp/src/hooks/useApi/query.ts
All variable names are entirely intentional
=> Add success callback

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap, src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Update/__snapshots__/EnrollmentUpdate.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/Fields/BirthCertificateFieldSet.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap
=> Fix horizontal bug

src/Hedwig/ClientApp/src/containers/BatchEdit/BatchEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/EnrollmentsEditList.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/SingleEnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/Fields/Funding/FirstReportingPeriod.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/Fields/Funding/index.tsx
=> 1192: moveNextEnrollment cycles through all enrollments missing info

src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/ContractSpace.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/WithNewFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/NewForm.tsx
encapsulates the funding creation logic inside the funding option expansion, where it actually should belong
(realized while doing change enrollment work that this had holes; this is not just some correctness pursuit but was actually broken)
=> Realized this wasn't working how it actually needed to work

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/assets/styles/_general.scss, src/Hedwig/ClientApp/src/components/SideNav/SideNav.stories.tsx, src/Hedwig/ClientApp/src/components/SideNav/SideNav.tsx, src/Hedwig/ClientApp/src/components/SideNav/SideNavItem.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/EnrollmentsEditList.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/SingleEnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/ChildInfo/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/ContractSpace.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/WithNewFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/index.tsx
Should close #1188 and close #1189
=> Add all done message for batch edit

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx
=> Fix roster link bug

src/Hedwig/ClientApp/src/containers/Withdrawal/Fields/EnrollmentEndDate.tsx
=> Fix withdrawal c4k bug

src/Hedwig/ClientApp/src/components/StepList/_index.scss, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/NewForm.tsx
Closes #1206 .  A note that this is a tiny departure from the initial design.
=> Adjust padding in embedded step list to allow for error messages

src/Hedwig/ClientApp/src/components/Form_New/FormField.tsx, src/Hedwig/ClientApp/src/components/RadioButtonGroup/RadioButtonGroup.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/EnrollmentFunding/EditForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/__snapshots__/EnrollmentNew.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Update/EnrollmentUpdate.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Update/__snapshots__/EnrollmentUpdate.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/Fields/Gender.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/Fields/Race.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Care4Kids/CertificateStartDate.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Care4Kids/FamilyId.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/EnrollmentEndDate.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/EnrollmentStartDate.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/FirstReportingPeriod.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/LastReportingPeriod.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/WithNewFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Funding/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/Site.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/common.ts, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/NewForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/Care4Kids/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/EnrollmentCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/EnrollmentFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/NewEnrollmentFundingFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/common.ts, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/index.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Fields/LastReportingPeriod.tsx, src/Hedwig/ClientApp/src/utils/models/enrollment/enrollment.ts, src/Hedwig/Models/Funding/LastReportingPeriodResolver.cs
should close #1156 
tests forthcoming
=> 1156: User can change enrollment

.gitignore, src/Hedwig/ClientApp/src/components/DateRangeInput/DateRangeInput.tsx, src/Hedwig/ClientApp/src/components/ErrorBoundary/ErrorBoundary.tsx, src/Hedwig/ClientApp/src/components/FieldSet/FieldSet.tsx, src/Hedwig/ClientApp/src/containers/App/App.module.scss, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/ChildInfo.test.tsx
Misc cleanup from todo spelunking expedition
=> Review todos

src/Hedwig/ClientApp/src/containers/BatchEdit/EnrollmentsEditList.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/SingleEnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/EnrollmentFunding/EditForm.tsx
also, fixes the weirdness with move next enrollment on last enrollment
closes #1225
=> 1225: DIsplays enrollmentFunding section when c4k info missing

src/Hedwig/ClientApp/src/containers/BatchEdit/BatchEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/EnrollmentsEditList.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx
Very draft because quite hacky. If anyone has ideas for how to handle history better please let me know!!!!
closes #1210
=> 1210: Batch edit from report roster

src/Hedwig/ClientApp/src/containers/Enrollment/Update/__snapshots__/EnrollmentUpdate.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/ChangeFundingFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/EndFundingFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/FundingFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/UpdateForm/EnrollmentFunding/index.tsx
=> 1157: Adds ability to end current funding and start new funding

azure-pipelines.yml, src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/src/containers/BatchEdit/BatchEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/EnrollmentsEditList.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/SingleEnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/ChildInfo/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/EnrollmentFunding/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyIncome/EditForm.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyIncome/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyInfo/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/utils.ts, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx, src/Hedwig/ClientApp/src/utils/validations/getMissingInfoPrettyString.ts, src/Hedwig/ClientApp/yarn.lock, src/Hedwig/Repositories/ReportRepository.cs
=> 1253 batch edit has report enrollments

src/Hedwig/Models/Enrollment/EnrollmentProfile.cs, src/Hedwig/Models/Enrollment/PastEnrollmentDTO.cs, test/HedwigTests/Integrations/EnrollmentsControllerIntegrationTests.cs
=> 1267: Add back missing pastenrollments to EnrollmentDTO

README.md
Just to save any future versions of myself from more headache.
=> Add note to README about Docker memory requirements

src/Hedwig/ClientApp/src/containers/BatchEdit/BatchEdit.test.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/BatchEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/EnrollmentsEditList.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/__snapshots__/BatchEdit.test.tsx.snap
=> 1265: Update batch edit subheader text as enrollments are completed

.circleci/config.yml
Closes https://github.com/ctoec/data-collection/issues/403.
-----------------------------------------------------------------------------------------------------------------------
- https://github.com/ctoec/winged-keys/pull/60
- https://github.com/skylight-hq/ctoec-devops/pull/138
=> Add prod deploy pipeline

.circleci/config.yml, src/Hedwig/.ebextensions/https-instance.config
Necessary for us to pull said certificates and keys out of source control!
------------------------------------------------------------------------------------------------------------------------
- https://github.com/skylight-hq/ctoec-devops/pull/132
- https://github.com/ctoec/data-collection/pull/647
- https://github.com/ctoec/winged-keys/pull/59
=> Pull SSL Certificate and Key directly from S3
