azure-pipelines.yml, hedwig.csproj
The driver file was changed to publish to the sonarcloud xhedwig project (temporary sonar project).  Each project in sonarcloud requires a unique GUID.  The GUID was changed for the hedwig project to be unique (not the same as the prototype project).
=> add sonarcloud support for hedwig (#28)

src/Hedwig/ClientApp/src/assets/styles/index.scss, src/Hedwig/ClientApp/src/assets/styles/print.scss
Simplify implementation for User story #3. This PR adds a print style sheet with the use of CSS media queries.
This implementation has a known limitation on being able to render a display on Firefox in the browser. This is due to how Firefox implements printing (versus Chrome-based browsers). For an implementation that provides a potential solution, see #34 (on branch 3-print-roster-with-context).
=> Add print stylesheet

docker-compose.yaml
This change gives about a 25% performance boost on Macs. See: https://docs.docker.com/docker-for-mac/osxfs-caching/
=> Switch to mounting volumes using the cached option

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/Reports/Reports.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/generated/AppQuery.ts, src/Hedwig/ClientApp/src/generated/ReportsQuery.ts, src/Hedwig/ClientApp/src/generated/RosterQuery.ts, src/Hedwig/ClientApp/src/hooks/useAuthQuery.ts
Include access token as a Bearer Token in all graphql requests.
Create a wrapper around `useQuery` hook so queries requiring authentication will instead use `useAuthQuery` -- with the same API.
Update queries from `user(id: 1)` to `me`.
Initial page load will show no data and "Log in" in the header. Clicking on login will redirect user to IS and then redirect back to roster page. After some time (initial load is slow) the data will load and "Log in" will be replaced with "Hi, Chris". Currently, no loading sign exists for after redirect.
=> Add graphql frontend auth (97)

src/Hedwig/Security/AuthorizationEvaluator.cs, src/Hedwig/Security/AuthorizationMetadataExtensions.cs, src/Hedwig/Security/AuthorizationRule.cs, src/Hedwig/Security/AuthorizationRules.cs, src/Hedwig/Security/AuthorizationValidationRule.cs, src/Hedwig/Security/IAuthorizedGraphType.cs, src/Hedwig/ServiceExtensions.cs
Due to the limitations of GraphQL.Authorization, this PR pulls several key files into our code base and modifies them to support an authorization flow similar to iptables.
Files that are pulled in are denoted with the GraphQL.Authorization's license at the start of the file with a link to the fixed Github file.
This needs tests, but I wanted to get it out there to see if the permissions flow makes sense.
How it would work in practice:
In a `HedwigGraphType` class, such as `UserType` is must implement the `IAuthorizedGraphType` interface and implement the `Permissions` method like so
```cs
public AuthorizationRules Permissions(AuthorizationRules rules)
{
rules.DenyNot("IsAuthenticatedUserPolicy");
rules.Allow();
return rules;
}
```
=> Modify GraphQL.Authorization to support iptables-like permissions

auth-dev/OpenIDProvider/Config.cs, docs/graphql-authorization_10_24_2019.md, src/Hedwig/Schema/Types/ChildType.cs, src/Hedwig/Schema/Types/EnrollmentType.cs, src/Hedwig/Schema/Types/UserType.cs, src/Hedwig/Security/AuthorizationContext.cs, src/Hedwig/Security/AuthorizationEvaluator.cs, src/Hedwig/Security/AuthorizationMetadataExtensions.cs, src/Hedwig/Security/AuthorizationPolicy.cs, src/Hedwig/Security/AuthorizationPolicyBuilder.cs, src/Hedwig/Security/AuthorizationSettings.cs, src/Hedwig/Security/AuthorizationValidationRule.cs, src/Hedwig/Security/IAuthorizationRequirement.cs, src/Hedwig/Security/Permissions.cs, src/Hedwig/Security/Policies/CurrentUserRequirement.cs, src/Hedwig/Security/Policies/DeveloperUserRequirement.cs, src/Hedwig/Security/Policies/DevelopmentRequirement.cs, src/Hedwig/Security/Policies/TestModeRequirement.cs, src/Hedwig/ServiceExtensions.cs, src/Hedwig/Startup.cs, test/HedwigTests/Fixtures/TestAuthenticationHandler.cs, test/HedwigTests/Fixtures/TestClientProvider.cs, test/HedwigTests/Fixtures/TestServiceExtensions.cs, test/HedwigTests/Fixtures/TestStartup.cs
Add initial protection to API endpoints.
Several new requirements are added:
* `CurrentUserRequirement` --> the user query id is the authenticated user id
* `DeveloperUserRequirement` --> the user has the "developer" role claim
* `DevelopmentRequirement` --> the current environment is development
Pulls down more of the `GraphQL.Authorization` library; needed to allow requirements to inspect the arguments in queries.
Relies on more DI to support injecting `HedwigContext` and `IHostingEnvironment` objects into specific requirements, instead of carrying them along on the `RequestContext` object.
Should resolve #106
=> Add API endpoint protection (106)

src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Schema/Mutations/EnrollmentMutation.cs, src/Hedwig/ServiceExtensions.cs, test/HedwigTests/Integration/GraphQLMutations/EnrollmentMutationTests.cs
I have a question about the process for clearing an exit date (i.e. setting it to null). I'm not sure if this is a supported use case but needed to check in. /cc @cmgiven 
Should resolve #7
=> Add enrollment mutation

src/Hedwig/Program.cs, src/Hedwig/appsettings.json
This is for a future demo for application logging (with CloudWatch support) with team leaders for GitHub issue 51.  For more information on the suggested logging implementation, see:  https://github.com/ctoec/ecis-experimental/wiki/Paper:-Application-Logging.
This pull request is to ensure AWS logging does not occur in the development environment.  A conditional was added to the program.cs file. There is a hard code in the appsettings.json for Logging.Region.  If this appsettings value is empty (""), the CI build will fail. 
This issue will not be closed if the pull request gets merged.
=> application logging (#51)

src/Hedwig/GraphQL/CommitMutationFieldsMiddleware.cs, src/Hedwig/GraphQL/HedwigExecutor.cs, src/Hedwig/GraphQL/IFieldsMiddleware.cs, src/Hedwig/Repositories/ChildRepository.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/FamilyRepository.cs, src/Hedwig/Repositories/ReportRepository.cs, src/Hedwig/Repositories/UserRepository.cs, src/Hedwig/Schema/AppErrorMessages.cs, src/Hedwig/Schema/AppSchema.cs, src/Hedwig/Schema/Mutations/EnrollmentMutation.cs, src/Hedwig/Schema/Mutations/FamilyMutation.cs, src/Hedwig/Schema/Mutations/ReportMutation.cs, src/Hedwig/Schema/Queries/ChildQuery.cs, src/Hedwig/Schema/Queries/EnrollmentQuery.cs, src/Hedwig/Schema/Queries/ReportQuery.cs, src/Hedwig/Schema/Queries/UserQuery.cs, src/Hedwig/ServiceExtensions.cs, test/HedwigTests/Helpers/FamilyHelper.cs, test/HedwigTests/Integration/GraphQLMutations/FamilyMutationTests.cs, test/HedwigTests/Repositories/ReportRepositoryTests.cs
This adds the create family method to family and the update family method to child.
Removes saving changes to db context from repositories to a commit mutation middleware.
Cleans up async/await code.
Should resolve #169
=> 169 Add create family with child mutation

src/Hedwig/Repositories/FamilyDeterminationRepository.cs, src/Hedwig/Repositories/FamilyRepository.cs, src/Hedwig/Schema/Mutations/FamilyDeterminationMutation.cs, src/Hedwig/Schema/Types/FamilyDeterminationType.cs, src/Hedwig/ServiceExtensions.cs, test/HedwigTests/Integration/GraphQLMutations/FamilyDeterminationMutationTests.cs, test/HedwigTests/Repositories/FamilyDeterminationRepositoryTests.cs, test/HedwigTests/Repositories/FamilyRepositoryTests.cs
I opted to put the null-checking logic into the repository `UpdateFamilyDetermination` function, as opposed to handling it in the mutation itself. This was easy enough to do because none of the familydetermination fields are nullable; if they have a value, use it to update, if not then nothing changes. Not sure it's what we want to do / should do / can do for objects with nullable fields, but it seemed the cleanest here. 
closes #170 #176
=> 170: Add family determination mutations

docker-compose.yaml, rest-backend/db.json, rest-backend/routes.json
adds a simple json server to docker-compose project that serves static data at localhost:6000
missing: family not accessible via child route. we did not determine in API v2 Spec (#230) if we want to expose family on the child via an optional `include=family` or `includeFamily=true` qs param
closes #233
=> 233: Adds a mocked rest backend to the docker-compose project

docker-compose.yaml
This is a dependency of ctoec/winged-keys#11. Adds the database to the docker compose project.
=> (WingedKeys) Add database in docker compose

src/Hedwig/Controllers/OrganizationController.cs, src/Hedwig/Hedwig.csproj, src/Hedwig/Repositories/OrganizationRepository.cs, src/Hedwig/ServiceExtensions.cs
Should close #258 
Added Newtonsoft b/c the Dotnet Core 3 built-in is not feature-ful enough for our use case, re recursive serialization.
As part of this, I explored additional sub-field inclusion. ASPNet Core provides us great query string inspection that makes adding this super easy! Combined with EF's hydration support and we can do some fancy things!
For example, try these queries:
* `/api/organizations/1`
* `/api/organizations/1?include[]=site`
* `/api/organizations/1?include[]=site&include[]=enrollment`
=> Add serializing support without DTO

src/Hedwig/Repositories/OrganizationRepository.cs, src/Hedwig/Repositories/PermissionRepository.cs, src/Hedwig/Repositories/SiteRepository.cs, src/Hedwig/Repositories/UserRepository.cs, src/Hedwig/Security_NEW/Requirements/IPermissionRequirement.cs, src/Hedwig/Security_NEW/Requirements/UserOrganizationAccessRequirement.cs, src/Hedwig/Security_NEW/Requirements/UserSiteAccessRequirement.cs, src/Hedwig/Security_NEW/RequirementsHandler.cs, src/Hedwig/ServiceExtensions.cs, src/Hedwig/Startup.cs, test/HedwigTests/Repositories/PermissionRepositoryTests.cs, test/HedwigTests/Security_NEW/Requirements/UserOrganizationAccessRequirementTests.cs, test/HedwigTests/Security_NEW/Requirements/UserSiteAccessRequirementTests.cs, test/HedwigTests/Security_NEW/RequirementsHandlerTests.cs
- Implements simple authorization requirements to enforce user access to an organization or a site; see: `Security_NEW/UserSiteAccessRequirement.cs` and `Security_New/UserOrganizationAccessRequirement.cs`
- Adds each custom requirement to an authorization policy; see: `ServiceExtensions.cs` and `Startup.cs`
- Adds a multi-policy AuthorizationHandler, called `PermissionHandler` for now copied from a microsoft example, but maybe confusing since nothing else is called "permissions"; see: `Secutiry_NEW/PermissionHandler.cs`
note: this does not explicitly add an authenticated user requirement. the requirement is implicit in the other requirements. this may not be the best design.
TODO: actually implement the PermissionRepository code for user/site and user/organization logic
closes #232
=> 232 authorization

src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Migrations/20191126205406_AddWingedKeysIdToUser.Designer.cs, src/Hedwig/Migrations/20191126205406_AddWingedKeysIdToUser.cs, src/Hedwig/Models/User.cs, src/Hedwig/Repositories/UserRepository.cs, src/Hedwig/Schema/Queries/UserQuery.cs, test/HedwigTests/Helpers/UserHelper.cs, test/HedwigTests/Integration/GraphQLQueries/UserQueryPermissionsTests.cs
Add `WingedKeysId` to `User` model because WingedKeys expects a Guid as the `sub` claim.
=> Prepare for WingedKeys users table

src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/utils/ageGroupUtils.ts
I left some code in that became obsolete with @mmazanec22's `AgeGroupSection` refactor. This removes this and tightens typings.
=> Clean up roster from deepnonundefineable type changes

src/Hedwig/ClientApp/src/utils/models/child.ts
`childArgsAreValid` never returns true -- only false and undefined, so we can never save
=> Make childArgsAreValid return true

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/enrollmentTypes.tsx
This means status is correctly reported in new and edit enrollment view
addresses #157  but does not add inline icons to missing fields
=> 157: Streamline section status reporting

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/generated/models/Gender.ts, src/Hedwig/ClientApp/src/utils/models/gender.ts, src/Hedwig/Models/Gender.cs
Connects #450.
Note that this pulls a switcheroo on enum values. Considered this okay because there's no prod data and test data is wiped and reseeded constantly.
=> Add nonbinary gender option

src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/contexts/ReportingPeriod/ReportingPeriodContext.tsx, src/Hedwig/ClientApp/src/generated/apis/HedwigApi.ts, src/Hedwig/ClientApp/src/index.tsx, src/Hedwig/ClientApp/src/utils/fundingTimeUtils.ts, src/Hedwig/ClientApp/src/utils/models/familyDetermination.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/ClientApp/src/utils/models/index.ts, src/Hedwig/ClientApp/src/utils/models/reportingPeriod.ts, src/Hedwig/ClientApp/src/utils/types.ts, src/Hedwig/Controllers/ReportingPeriodController.cs, src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Models/Funding.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/FundingRepository.cs, src/Hedwig/Repositories/ReportRepository.cs, src/Hedwig/Repositories/ReportingPeriodRepository.cs, src/Hedwig/ServiceExtensions.cs, test/HedwigTests/Helpers/FundingHelper.cs, test/HedwigTests/Helpers/ReportHelper.cs, test/HedwigTests/Helpers/ReportingPeriodHelper.cs, test/HedwigTests/Repositories/ReportRepositoryTests.cs
* Updates backend enrollment save to support updating funding --> because the mapping for fundings <--> enrollment lives on funding, we cannot just use _context.Update(enrollment) and instead need to inspect the fundings pointing to enrollment.Id. And then ef is very opininated on the order of everything and aggressive tracking.
* Creates backend reportingperiod controller. I feel like there should be a better way for all of this reporting period stuff given it lives so far away (within the db) to funding.
* Creates reportingperiod repo
* Adds in smarter typings for removing the type predicate =/= bool problem
* A fair amount of ui wrangling -- several utils updates to summary and form and some strong-ish assumptions. /shrug/
Should close #150
URL: ....
=> Add ability for selecting CDC funding / private pay during enrollment

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/generated/models/Funding.ts, src/Hedwig/Migrations/20200101153302_AddFamilyIdToFunding.Designer.cs, src/Hedwig/Migrations/20200101153302_AddFamilyIdToFunding.cs, src/Hedwig/Models/Funding.cs
Should close #458 
The fundings (and updated fundings) array update logic can probably be cleaned up. See #482 
@atreni: It didn't look like there was info on the comp (https://skylight.invisionapp.com/public/share/FZWU9IO32#/screens/391165739) about what to show in the summary view. Let me know if there should be any changes from my assumptions here.
URL: https://3.15.236.11:5001
=> Add FamilyId to Funding and C4K ui selection

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/utils/validations/index.ts, src/Hedwig/ClientApp/src/utils/validations/useFocusFirstError.ts
Closes #534 and #535.
Also shows an error instead of a blank page on a 500, but does not fix that reports are currently unable to be submitted due to an undiagnosed 500 error.
=> Jump to first input field with a blocking error

src/Hedwig/Validations/Rules/ConditionalFieldRequired.cs, src/Hedwig/Validations/Rules/FieldRequired.cs, test/HedwigTests/Validations/Rules/ConditionalFieldRequiredTests.cs, test/HedwigTests/Validations/Rules/FieldRequiredTests.cs, test/HedwigTests/Validations/TestValidatableEntity.cs
This is how dotnet core does it as well (aka why our required FirstName and LastName are appropriate failing when we send empty string)
=> 509: Fixes bad validations around empty strings

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/utils/validations/initialLoadErrorGuard.ts
Should close #589 
This uses the `visitedSections` object that #582 introduced to only show errors after a using has hit save at least once in the section.
=> Add InitialLoadingErrorGuard

src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx
I had ditched the onChange in a previous PR to make it not infinitely loop; this addresses it using useCallback to avoid both warning and infinite loop.
=> Ditch date input warning and even out button spacing

src/Hedwig/ClientApp/src/contexts/ReportingPeriod/ReportingPeriodContext.tsx, src/Hedwig/ClientApp/src/generated/apis/HedwigApi.ts, src/Hedwig/Controllers/ReportingPeriodsController.cs, test/HedwigTests/Controllers/ReportingPeriodsControllerTests.cs, test/HedwigTests/Repositories/ReportingPeriodRepositoryTests.cs
also renames ReportingPeriodController (and thus api route) to idiomatic
ReportingPeriodsController
closes #512
=> 512: Adds tests for reporting period

src/Hedwig/Data/DbInitializer.cs, src/Hedwig/Data/HedwigContext.cs, src/Hedwig/Models/Attributes/ReadOnlyAttribute.cs, src/Hedwig/Models/ReportingPeriod.cs, test/HedwigTests/Data/HedwigContextTests.cs, test/HedwigTests/Helpers/ReportingPeriodHelper.cs, test/HedwigTests/Models/Attributes/ReadOnlyAttributeTests.cs
closes #700 
NOTE: With this impl, updates to read-only fields fail silently. I think this is pref to a failed POST/PUT, but interested in other's thoughts. I have not found a way to add warnings to an arbitrary API response (looked into this when thinking thru the non-blocking model validations) that seems idiomatic or not overly cumbersome. But can revisit if others think silently throwing away updates to read only is not acceptable.
=> 700: Adds ReadOnly entity and applies to ReportingPeriod

docs/backend/2020_02_05_read-only-entities.md
does this merit a LAD? Felt like there was some context that would be nice to have in perpetuity riding along with source, which is p much what i understand LADs to be for :)
=> Adds LAD for read-only entity impl

src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/App/__snapshots__/App.test.tsx.snap
Sorry I didn't catch this on the PR. As a general rule, we're using sentence case everywhere in the app (ironically, the policy itself is the only exception I can think of).
=> Use sentence case for privacy policy link

azure-pipelines.yml
In the azure pipeline, test results are not published on failure.
May be due to the test task exiting with exit code from container. This was implemented to ensure that if the application build orchestrated by docker before running the tests failed, the whole pipeline failed.
AC:
test results are published on success or failure
somewhere in the pipeline, a failed app build causes pipeline failure
=> publish test on success or failure (#745)

src/Hedwig/Data/HedwigContext.cs, src/Hedwig/Repositories/EnrollmentRepository.cs
closes #757 in a kind of hacky or at least not the most forward-looking way 
NOTE: this fix is needed b/c references to the same user object in
multiple obejcts in the PUT data (i.e. on enrollment, child, family,
etc) lead to a dbContext error and 500 response. Is this going to be a
problem moving forward? Do we eventually need DTOs ?
(this issue will only be caught by integration test w/ real backend, so will add tests after selenium integration is in. ticket here:
=> Fixes a bug that breaks enrollment updates

src/Hedwig/ClientApp/package.json, src/Hedwig/ClientApp/public/config.json, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts, src/Hedwig/ClientApp/src/index.tsx, src/Hedwig/ClientApp/yarn.lock
Sentry needs to be setup within the Hedwig react front end. This integration is highly documented in articles like:
* https://docs.sentry.io/platforms/javascript/react
The Hedwig react code, the Sentry properties will be in the public/config.json file as follows:
````
{
"Sentry.FEDsn": "",
"Sentry.Release": ""
}
````
This issue closes #751
=> 751: Adds sentry integration to client

src/Hedwig/ClientApp/src/components/Alert/Alert.tsx, src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/enrollmentTypes.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts, src/Hedwig/ClientApp/src/hooks/useApi.ts, src/Hedwig/ClientApp/src/utils/stringFormatters/alertTextMakers.tsx, src/Hedwig/ClientApp/src/utils/validations/errorForField.ts, src/Hedwig/ClientApp/src/utils/validations/index.ts, src/Hedwig/ClientApp/src/utils/validations/initialLoadErrorGuard.ts, src/Hedwig/ClientApp/src/utils/validations/isBlockingValidationError.ts
Repurposes the `error` entity of `ApiState` from `useApi` to pass around errors for pages using the associated apistate entity and api mutate function for that entity. 
Adds handling for un-UI-handled errors 
closes #710
=> 710 uncaught api error

src/Hedwig/Repositories/EnrollmentRepository.cs
Unblocks creating and updating enrollments by removing the conflicting
author User entity
This is a temporary fix until DTOs are implemented
NOTE: This results in the enrollment update metadata info missing from
UI, however all the parts are still there and we will get this feature
back once author User references are back
needs: e2e tests to confirm each enrollment section can be saved
closes #781
=> 781: Fixes enrollment save bug

src/Hedwig/Controllers/EnrollmentsController.cs
before change enrollments query size: 1.6MB
after change: 55.4MB
before change enrollments query time: ~1000ms
after change: ~600ms
=> 777: Quick fix to improve performance

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Edit/EnrollmentEdit.test.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/New/EnrollmentNew.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportDetail.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/__snapshots__/ReportSubmitForm.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/ReportsSummary.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.test.tsx, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/Hedwig/ClientApp/src/contexts/__mocks__/TestProvider.tsx, src/Hedwig/ClientApp/src/hooks/__mocks__/useApi.ts, src/Hedwig/ClientApp/src/tests/data/child.ts, src/Hedwig/ClientApp/src/tests/data/enrollment.ts, src/Hedwig/ClientApp/src/tests/data/index.ts, src/Hedwig/ClientApp/src/tests/data/organization.ts, src/Hedwig/ClientApp/src/tests/data/report.ts, src/Hedwig/ClientApp/src/tests/data/reportingPeriod.ts, src/Hedwig/ClientApp/src/tests/data/site.ts, src/Hedwig/ClientApp/src/tests/data/user.ts
Simplifies `CommonContextMockProvider` and `useApi` mock. Mostly addresses the issue that Chris identified in the report tests -- I think this is much cleaner.
Does have the downside that import order matters but I am comfortable with that tradeoff
=> Refactor tests

src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyInfo.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/hooks/useApi.ts
@jlhogan you were right that this would fix #834 -- the error check in the child info promise was getting the old error from the first save attempt.
=> Update mutate error return

azure-pipelines.yml
Microsoft has broken its own product via an update. As a result, the PR and CI builds are not automatically triggering. As a workaround, they must be manually started. To resolve the issue Microsoft recommends to explicitly identify the triggers in the YAML file.
For more information, see https://developercommunity.visualstudio.com/content/problem/948871/github-is-not-able-to-trigger-ado-pipeline-builds.html
=> fix pull request auto-trigger issue (#869)

src/Hedwig/Repositories/ReportingPeriodRepository.cs, src/Hedwig/Validations/Attributes/Enrollment/CDC_Funding_ReportingPeriodsAreValid.cs, src/Hedwig/Validations/Rules/FamilyDetermination/IfEnrollmentFunded_DeterminationDateValid.cs, test/HedwigTests/Validations/Rules/FamilyDetermination/IfEnrollmentFunded_DeterminationDateValidTests.cs
this is a not-nice outcome of un-setting read only properties before validation time.. however, I'm in the process of turning validation into a filter as well, which can run before the unset ! and then we can undo this. 
this fixes the existing reporting submissing failure in staging blocking prod deploy
=> Add references for reporting periods in validations

src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/generated/apis/HedwigApi.ts, src/Hedwig/ClientApp/src/generated/models/Enrollment.ts, src/Hedwig/Controllers/ChildrenController.cs, src/Hedwig/Filters/TransformEntityFilterAttribute.cs, src/Hedwig/Models/Attributes/PropertyInfoExtensions.cs, src/Hedwig/Models/Enrollment.cs, src/Hedwig/Repositories/ChildRepository.cs, src/Hedwig/Repositories/EnrollmentRepository.cs, src/Hedwig/Repositories/HedwigRepository.cs, src/Hedwig/Validations/NonBlockingValidationContext.cs, src/Hedwig/Validations/NonBlockingValidator.cs, test/HedwigTests/Repositories/ChildRepositoryTests.cs, test/HedwigTests/Repositories/EnrollmentRepositoryTests.cs
Altho I think it'll ultimately be better to use child as the root object in the enrollment detail flow, it was snowballing into a bigger change. This unblocks creating frontend utils to create enrollment history, which will still be mostly applicable when/if we decide to do the refactor. 
closes #908
=> Past enrollments

src/Hedwig/Startup.cs
Fix issue (#1017)
Startup.cs contains the following line:
- var isAutomaticallyApplyMigrations = EnvironmentConfiguration.GetEnvironmentVariableFromAppSettings("AutomaticallyApplyMigrations")
This line should be:
- var isAutomaticallyApplyMigrations = EnvironmentConfiguration.GetEnvironmentVariableFromAppSettings("Database:AutomaticallyApplyMigrations")
=> startup.cs - fixed app settings reference for database

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/ButtonWithDropdown/ButtonWithDrowdown.tsx, src/Hedwig/ClientApp/src/components/Card/Card.tsx, src/Hedwig/ClientApp/src/components/CheckboxGroup/CheckboxGroup.tsx, src/Hedwig/ClientApp/src/components/ChoiceList/ChoiceList.tsx, src/Hedwig/ClientApp/src/components/DateInput/DateInput.tsx, src/Hedwig/ClientApp/src/components/Form/Form.tsx, src/Hedwig/ClientApp/src/components/Form/FormField.tsx, src/Hedwig/ClientApp/src/components/ProcessList/ProcessStep.tsx, src/Hedwig/ClientApp/src/components/RadioButtonGroup/RadioButtonGroup.tsx, src/Hedwig/ClientApp/src/components/SideNav/SideNav.tsx, src/Hedwig/ClientApp/src/containers/App/App.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/ReportsSummary.test.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportsSummary/__snapshots__/ReportsSummary.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Roster/Roster.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/hooks/useApi/query.ts, src/Hedwig/ClientApp/src/hooks/useCatchallErrorAlert.ts, src/Hedwig/ClientApp/src/utils/fundingType.tsx, src/Hedwig/ClientApp/src/utils/models/family.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/ClientApp/src/utils/validations/displayValidationStatus.ts, src/Hedwig/ClientApp/yarn.lock
Addresses some easy wins for clean up.
Most of the warnings in the enrollment sections are left so as to not conflict with the refactor.
Some other warnings are left because they may require larger overhead to fix, namely most of the remaining useEffects dependencies issues.
=> Clean up some react warnings and errors

src/Hedwig/ClientApp/src/components/Form_New/Form.tsx, src/Hedwig/ClientApp/src/components/Form_New/FormContext.ts, src/Hedwig/ClientApp/src/components/Form_New/index.ts, src/Hedwig/ClientApp/src/components/Select/Select.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/UpdateForm/FamilyDeterminationFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/ReportSubmitForm.tsx, src/Hedwig/ClientApp/src/containers/Reports/ReportDetail/UtilizationTable.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Fields/EnrollmentEndDate.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Fields/ExitReason.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Fields/LastReportingPeriod.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/__snapshots__/Withdrawal.test.tsx.snap, src/Hedwig/ClientApp/src/utils/models/enrollment/enrollment.ts, src/Hedwig/ClientApp/src/utils/models/funding.ts, src/Hedwig/ClientApp/src/utils/models/fundingSpace.ts, src/Hedwig/ClientApp/src/utils/stringFormatters/splitCamelCase.ts, src/Hedwig/ClientApp/src/utils/utilizationTable.tsx, src/Hedwig/ClientApp/src/utils/validations/messageStrings.ts
Should close #1133 
Updates Withdrawal to use our new form component. It takes inspiration of a `mutatedEnrollment` state variable a la `ChildInfo/NewForm`.
Also adds logic to prevent the last reporting period dropdown from showing a reporting period before the first reporting period.
Includes a few updates to form to allow for function style state update and updates to utils to support removing DeepNonUndefinable.
=> Refactor Withdrawal page to use new form

src/Hedwig/ClientApp/src/containers/Roster/AgeGroupSection.tsx, src/Hedwig/ClientApp/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
Should close #1082 
A stop gap measure to make the column consistent. I think the issue is that the table width percentages are not fully deterministic and influenced by the full string of the site name (before truncation). So the site column steals space from other columns, making them smaller and pushing the columns out of alignment. Not really sure how to fix that.
Rider: Adds title attribute so hovering over the text shows the full name
=> Change column widths to be consistent across empty tables

src/Hedwig/ClientApp/src/containers/CommonContainer.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/EnrollmentDetail.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Detail/__snapshots__/EnrollmentDetail.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/Update/EnrollmentUpdate.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/Update/__snapshots__/EnrollmentUpdate.test.tsx.snap, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/Fields/FirstName.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/ChildInfo/Fields/LastName.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/Fields/Funding/ContractSpace.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/Fields/Funding/FirstReportingPeriod.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/Fields/Funding/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/Fields/common.ts, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/NewForm.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/UpdateForm/EnrollmentFunding/FundingCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/UpdateForm/EnrollmentFunding/FundingFormForCard.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/UpdateForm/EnrollmentFunding/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/UpdateForm/common.ts, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/UpdateForm/index.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding_NEW/index.ts, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/UpdateForm/FamilyDeterminationCard.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/Withdrawal.tsx, src/Hedwig/ClientApp/src/containers/Withdrawal/__snapshots__/Withdrawal.test.tsx.snap, src/Hedwig/ClientApp/src/contexts/History/HistoryContext.tsx, src/Hedwig/ClientApp/src/index.tsx
Should close #1066 
GOING THROUGH ALL THAT REACT INTERNAL CODE HAS PAID OFF BECAUSE IT SHOWED LIGHT ON THE FIBER DATA STRUCTURE (basically just a linked list) AND ITS VALUE WITHIN THE REACT LIFECYCLE
=> Add history context for location fiber

src/Hedwig/ClientApp/src/__snapshots__/storyshots.test.ts.snap, src/Hedwig/ClientApp/src/components/SideNav/SideNav.stories.tsx, src/Hedwig/ClientApp/src/components/SideNav/SideNav.tsx, src/Hedwig/ClientApp/src/components/SideNav/SideNavItem.tsx, src/Hedwig/ClientApp/src/components/SideNav/_index.scss
this was motivated by how the sidenav is used in the specs for batchedit, specifically:
- need to control cycle logic beyond just via clicks (i.e. completing the last enrollment in sidenav list will cycle back to first enrollment that still has missing info, or if no enrollment with missing info then no item selected)
- need to display content when no item is selected 
it does this by exposing the active item index. Not sure how we feel about exposing the index to the user to control selection (vs some other more logical means) BUT since it is a *list* i figured some sort of ordering was reasonable to assume & leverage.
=> 947: Update sidenav to function more like tabnav

src/Hedwig/ClientApp/src/components/StepList/StepList.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/SingleEnrollmentEdit.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/ChildInfo/EditForm.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/EnrollmentFunding/EditForm.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/EnrollmentFunding/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyIncome/EditForm.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyIncome/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyInfo/EditForm.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/FamilyInfo/index.tsx, src/Hedwig/ClientApp/src/containers/BatchEdit/_sections/batchEditTypes.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/EnrollmentFunding/Fields/AgeGroup.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Fields/AnnualHouseholdIncome.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Fields/DeterminationDate.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Fields/HouseholdSize.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Fields/IncomeDeterminationFieldSet.tsx, src/Hedwig/ClientApp/src/containers/Enrollment/_sections/FamilyIncome/Fields/common.ts
closes #1186, closes #1187 
also makes 'editPath' on external SectionProps optional to match internal defn, and remove need for empty prop on batch edit sections
=> 1186 batch edit enrollment funding

.circleci/config.yml
PR to update the path where Hedwig secrets are stored in CircleCI, so that deploys can continue without issue.  Said path was unfortunately necessarily updated in https://github.com/skylight-hq/ctoec-devops/pull/96.
=> Match updated secrets location

src/Hedwig/.ebextensions/https-instance.config
This hack has since been [moved to Terraform](https://github.com/skylight-hq/ctoec-devops/pull/150), so at least it lives in one place and not three.
---------------------------------------------------------------------------------------------------------------------------
- https://github.com/skylight-hq/ctoec-devops/pull/150
- https://github.com/ctoec/winged-keys/pull/63
- https://github.com/ctoec/data-collection/pull/755
=> Remove default EC2 security group deletion hack
